package pe.gob.oefa.efa.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Supervisor generated by hbm2java
 */
@Entity
@Table(name = "efa_supervisor")
public class Supervisor implements java.io.Serializable {

	private BigDecimal idsupervisor;
	private String dni;
	private String appPaterno;
	private String appMaterno;
	private String nombre;
	private String sexo;
	private Date fechaNac;
	private String telefono;
	private String direccion;
	private String departamento;
	private String provincia;
	private String distrito;
	private String estadoCivil;
	private String profesion;
	private String correo;
	private Date iniLaboral;
	private Date finLaboral;
	private String modalidad;
	private String nroContrato;
	private String remuneracion;
	private String cargo;
	private String correoIns;
	private String cuentaBco;
	private String otroBco;
	private String otroBcoNro;
	private Set<SupervisorFile> supervisorFiles = new HashSet<SupervisorFile>(0);
	private Set<SupervisorEmergencia>  supervisorEmergencias = new HashSet<SupervisorEmergencia>(0);
	private Set<Actividad> actividades = new HashSet<Actividad>(0);

	private String flgactivo;
	
	public Supervisor() {
	}

	public Supervisor(BigDecimal idsupervisor) {
		this.idsupervisor = idsupervisor;
	}

	public Supervisor(BigDecimal idsupervisor, String dni, String appPaterno,
			String appMaterno, String nombre, String sexo, Date fechaNac,
			String telefono, String direccion, String departamento,
			String provincia, String distrito, String estadoCivil,
			String profesion, String correo, Date iniLaboral, Date finLaboral,
			String modalidad, String nroContrato, String remuneracion,
			String cargo, String correoIns, String cuentaBco,
			String otroBco, String otroBcoNro,
			Set<SupervisorFile> supervisorFiles, Set<SupervisorEmergencia> supervisorEmergencias, Set<Actividad> actividades) {
		this.idsupervisor = idsupervisor;
		this.dni = dni;
		this.appPaterno = appPaterno;
		this.appMaterno = appMaterno;
		this.nombre = nombre;
		this.sexo = sexo;
		this.fechaNac = fechaNac;
		this.telefono = telefono;
		this.direccion = direccion;
		this.departamento = departamento;
		this.provincia = provincia;
		this.distrito = distrito;
		this.estadoCivil = estadoCivil;
		this.profesion = profesion;
		this.correo = correo;
		this.iniLaboral = iniLaboral;
		this.finLaboral = finLaboral;
		this.modalidad = modalidad;
		this.nroContrato = nroContrato;
		this.remuneracion = remuneracion;
		this.cargo = cargo;
		this.correoIns = correoIns;
		this.cuentaBco = cuentaBco;
		this.otroBco = otroBco;
		this.otroBcoNro = otroBcoNro;
		this.supervisorFiles = supervisorFiles;
		this.supervisorEmergencias = supervisorEmergencias;
		this.actividades = actividades;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	public BigDecimal getId() {
		return this.idsupervisor;
	}
	
	public void setId(BigDecimal idsupervisor) {
		this.idsupervisor = idsupervisor;
	}
	@Column
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}
	@Column(name="APPATERNO")
	public String getAppPaterno() {
		return this.appPaterno;
	}

	public void setAppPaterno(String appPaterno) {
		this.appPaterno = appPaterno.toUpperCase();
	}
	@Column(name="APMATERNO")
	public String getAppMaterno() {
		return this.appMaterno;
	}

	public void setAppMaterno(String appMaterno) {
		this.appMaterno = appMaterno.toUpperCase();
	}
	@Column
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre.toUpperCase();
	}
	@Column
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo.toUpperCase();
	}
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name="FECHA_NAC")
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}
	@Column
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	@Column
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	@Column
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}
	@Column
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}
	@Column
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}
	@Column(name="ESTADO_CIVIL")
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}
	@Column
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}
	@Column
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name="INI_LABORAL")
	public Date getIniLaboral() {
		return this.iniLaboral;
	}

	public void setIniLaboral(Date iniLaboral) {
		this.iniLaboral = iniLaboral;
	}
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name="FIN_LABORAL")
	public Date getFinLaboral() {
		return this.finLaboral;
	}

	public void setFinLaboral(Date finLaboral) {
		this.finLaboral = finLaboral;
	}
	@Column
	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}
	@Column(name="NRO_CONTRATO")
	public String getNroContrato() {
		return this.nroContrato;
	}

	public void setNroContrato(String nroContrato) {
		this.nroContrato = nroContrato;
	}
	@Column
	public String getRemuneracion() {
		return this.remuneracion;
	}

	public void setRemuneracion(String remuneracion) {
		this.remuneracion = remuneracion;
	}
	@Column
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}
	@Column(name="CORREO_INS")
	public String getCorreoIns() {
		return this.correoIns;
	}

	public void setCorreoIns(String correoIns) {
		this.correoIns = correoIns;
	}
	@Column(name="CUENTA_BCO")
	public String getCuentaBco() {
		return this.cuentaBco;
	}

	public void setCuentaBco(String cuentaBco) {
		this.cuentaBco = cuentaBco;
	}

	@Column(name="OTRO_BCO")
	public String getOtroBco() {
		return this.otroBco;
	}

	public void setOtroBco(String otroBco) {
		this.otroBco = otroBco;
	}
	@Column(name="OTRO_BCO_NRO")
	public String getOtroBcoNro() {
		return this.otroBcoNro;
	}

	public void setOtroBcoNro(String otroBcoNro) {
		this.otroBcoNro = otroBcoNro;
	}
	@OneToMany(mappedBy = "supervisor")  	
	public Set<SupervisorFile> getSupervisorFiles() {
		return this.supervisorFiles;
	}

	public void setSupervisorFiles(Set<SupervisorFile> supervisorFiles) {
		this.supervisorFiles = supervisorFiles;
	}
	@OneToMany(mappedBy = "supervisor")  	
	public Set<SupervisorEmergencia> getSupervisorEmergencias() {
		return this.supervisorEmergencias;
	}

	public void setSupervisorEmergencias(Set<SupervisorEmergencia> supervisorEmergencias) {
		this.supervisorEmergencias = supervisorEmergencias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "supervisores")
	public Set<Actividad> getActividades() {
		return this.actividades;
	}
 
	public void setActividades(Set<Actividad> actividades) {
		this.actividades = actividades;
	}
	
	@Column
	public String getFlgactivo() {
		return flgactivo;
	}

	public void setFlgactivo(String flgactivo) {
		this.flgactivo = flgactivo;
	}	
	
	
	
	
}
