package pe.gob.oefa.efa.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SupervisorEmergencia generated by hbm2java
 */
@Entity
@Table(name = "efa_supervisor_emergencia")
public class SupervisorEmergencia implements java.io.Serializable {

	private BigDecimal id;
	private Supervisor supervisor;
	private String nombre;
	private String telefono;
	private String parentesco;

	public SupervisorEmergencia() {
	}

	public SupervisorEmergencia(BigDecimal id, Supervisor supervisor,
			String nombre) {
		this.id = id;
		this.supervisor = supervisor;
		this.nombre = nombre;
	}

	public SupervisorEmergencia(BigDecimal id, Supervisor supervisor,
			String nombre, String telefono, String parentesco) {
		this.id = id;
		this.supervisor = supervisor;
		this.nombre = nombre;
		this.telefono = telefono;
		this.parentesco = parentesco;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}
	
	@ManyToOne  
	@JoinColumn(name = "IDSUPERVISOR")  
	public Supervisor getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(Supervisor supervisor) {
		this.supervisor = supervisor;
	}
	@Column
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@Column
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	@Column
	public String getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(String parentesco) {
		this.parentesco = parentesco;
	}

}
